name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
    inputs:
      targetBranch:
        description: 'The existing branch name to release from, following the format: release-<major>.<minor>.<patch>(-rc[0-9]+)?*, e.g. release-0.0.1'
        required: true
      targetImg:
        description: 'The target image tag, e.g. v0.0.1-rc4-ak.1'
        required: true
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      - name: Set env vars from repo dispatch trigger
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "TARGET_IMG=${{ github.event.client_payload.target_img }}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=${{ github.event.client_payload.target_branch }}" >> $GITHUB_ENV
      - name: Set env vars from workflow manual trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "TARGET_IMG=${{ github.event.inputs.targetImg }}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=${{ github.event.inputs.targetBranch }}" >> $GITHUB_ENV
      - run: echo ${TARGET_IMG} ${TARGET_BRANCH}
